FROM node:18-alpine AS build
WORKDIR /app
COPY package.json package-lock.json* ./
ENV NODE_OPTIONS=--max-old-space-size=2048
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable-alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]