version: '3.8'
services:
  frontend:
    container_name: frontend-container
    build:
      context: ./frontend
      dockerfile: dockerfile  # Specify lowercase
    ports:
      - "4000:4000"
    environment:
      - REACT_APP_API_URL=http://backend-container:4500/api
    depends_on:
      - backend
    networks:
      - mern-network
    restart: always
  backend:
    container_name: backend-container
    build:
      context: ./backend
      dockerfile: dockerfile  # Ensure backend also uses lowercase if needed
    ports:
      - "4500:4500"
    environment:
      - MONGO_URL=mongodb://mongo-container:27017/product
      - JWT_SECRET=your_super_secret_key
      - PORT=4500
    depends_on:
      - mongo
    networks:
      - mern-network
    restart: always
  mongo:
    image: mongo
    container_name: mongo-container
    environment:
      - MONGO_INITDB_DATABASE=product
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network
    restart: always
volumes:
  mongo-data:
networks:
  mern-network:
    driver: bridge